### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Leouch1** [mgemperl/TrainingTweak#1]
crash on startup (even with mod disabled, you have to delete it from module folder to fix issue) 
[rgl_log_12064.txt](https://github.com/mgemperl/TrainingTweak/files/4460789/rgl_log_12064.txt)
[rgl_log_errors_12064.txt](https://github.com/mgemperl/TrainingTweak/files/4460791/rgl_log_errors_12064.txt)
[CrashUploader.7344.txt](https://github.com/mgemperl/TrainingTweak/files/4460792/CrashUploader.7344.txt)
in crashfolder there is nothing new ;/. NVM foced game to generate it
[rgl_log_17168.txt](https://github.com/mgemperl/TrainingTweak/files/4460820/rgl_log_17168.txt)
[rgl_log_errors_17168.txt](https://github.com/mgemperl/TrainingTweak/files/4460821/rgl_log_errors_17168.txt)
[stack.txt](https://github.com/mgemperl/TrainingTweak/files/4460822/stack.txt)
[user_config.txt](https://github.com/mgemperl/TrainingTweak/files/4460823/user_config.txt)
[crash_tags.txt](https://github.com/mgemperl/TrainingTweak/files/4460824/crash_tags.txt)
[engine_config.txt](https://github.com/mgemperl/TrainingTweak/files/4460825/engine_config.txt)
[module_list.txt](https://github.com/mgemperl/TrainingTweak/files/4460826/module_list.txt)

**Comment by Leouch1** [comment]
ok mods: atribute point every 2 level
banditlord

when I disable them both, crash didnt occur

**Comment by mgemperl** [comment]
Heh, and I was just about to post a response. Here it is (I'll post it on nexus too):

Thanks, I got them. And ProgramData isn't really a folder you'd expect to be hidden, so I occasionally get confused about it as well. 

Looking at the log, it seems the crash does happen when it starts trying to load mod submodules, but I can't find any detailed information about the cause, unfortunately.

The creator of bannerlord tweaks mentioned mod loading can get unstable right now if you have more than 16 modules loading (so 11 mods max), so you could try getting rid of some mods. Maybe you could try temporarily moving all mods except mine out of the Modules folder and seeing if it still crashes, just to see if that's the cause.

If it does still crash on startup while mine's the only one there, I think I'm just not familiar enough with the game to figure out what's going on at the moment. At that point, you could try this other mod, which also multiplies the training xp by the number of troops. It does quite a few other things too, but it should be configurable.
https://www.nexusmods.com/mountandblade2bannerlord/mods/153

**Comment by mgemperl** [comment]
If I'm understanding right and disabling a couple other mods helped, it seems like it was just a problem with having too many mods.

If that's the case, I'll try adding a note to description.

**Comment by mgemperl** [comment]
Or I guess those mods could've caused an issue... I'll try looking at them.
