### ISSUE TITLE
Crashing on tick to day

### ISSUE THREAD

**Issue by Sons-of-Man** [mgemperl/TrainingTweak#2]
![error2](https://user-images.githubusercontent.com/7313699/79636399-f7955000-813c-11ea-8590-fba40510044d.PNG)

Not entirely sure what is causing it, but I can run the game for a couple of hours and go through tons of days before it happens, so I am at a complete loss. I do run quite a few mods but none that I would think are conflicting as none alter anything to do with XP or perks, besides Community Patch with fixes perks, I have that at the very bottom of load order. Any help is appreciated!

Edit: Nevermind, of course when I say "I can run the game for a couple of hours", it immediately crashes a few seconds later after loading back in once it ticks to day. Hmm...

**Comment by Sons-of-Man** [comment]
Aaaand now I am getting this after having disabled your mod and testing out Tyni's Bannerlord Fixes and Adjustments, so I am really lost now. Everything was fine before! I did add a few new mods yesterday but too my knowledge none of these would conflict right?

**Prosperity Taxes** _(messes with prosperity and lets you tax higher/lower to control prosperity)_
**Improved Smithing** _(adds a few xml tweaks for smithing)_
**Tournaments XPanded** _(changes tournaments quite drastically)_
**Attribute Point Per Level** _(name sais it all)_
**V's No Player Clan Party Limit** _(name sais it all)_
**V's No Companion Limit** _(name sais it all)_
**V's Garrisons Don't Eat Nor Starve** _(removes the need for garrison troops to use food, so if a town is starving, only the milita will drain and not the precious garrison troops)_


Should mention this popped up after going through about 4 days or so and it crashed in between setting up camp for a siege.



![error3](https://user-images.githubusercontent.com/7313699/79636998-4218cb80-8141-11ea-9f81-adc62a9e1875.PNG)

**Comment by Sons-of-Man** [comment]
Here's my full load order, lazily done but I think I got most of the major mods in the right places, please do correct me if you can spot something wrong as I bet there is.

![load order](https://user-images.githubusercontent.com/7313699/79637333-295de500-8144-11ea-8604-b2155a480237.PNG)

**Comment by mgemperl** [comment]
Thanks for all the detailed information and troubleshooting. 

I think the game is just a bit unstable right now. 

The crash in my mod seems to happen when some data that should exist is missing in the game state, and I don't really understand why that's happening or even who's fault it is.

I'll be releasing a new version soon that just does nothing instead of causing a crash when that data is missing. It isn't a perfect solution, but hopefully it'll help make my mod a bit more stable.

**Comment by mgemperl** [comment]
I think I'll add a little debugging popup when data is missing to let the user know what's going on as well.

With an option to disable in the mod options, of course.

**Comment by mgemperl** [comment]
I've uploaded a new version [(1.0.5)](https://www.nexusmods.com/mountandblade2bannerlord/mods/255?tab=files) that acts more cautiously when asking for data, so please try it out and let me know if it works.

Also let me know if the new mod version displays any debugging notice boxes for you. That should help us narrow down the cause of the issue. (You can disable the debug notices in the mod options if they're a nuisance.)

**Comment by Sons-of-Man** [comment]
Sweet! Will check it out, actually just exited out to do daily mod updating, lol. I solved my 2nd problem for now at least, for whatever reason my game did not like Tyni's Bannerlord Adjustments and Fixes, removing that has so far yielded 0 crashes after probably 80 days or so now. Crossing my fingers the new update for Training Tweaks works! Can't live without it.

**Comment by mgemperl** [comment]
Yeah, playing this game with the Native training is painful, and I'm not aware of any mods other than mine and Tyni's that fix it (I haven't looked very hard though).

Here's hoping this new update works, or at least gives a hint regarding the problem.

**Comment by Sons-of-Man** [comment]
So far so good. 20 days in and nothing appears to have gone wrong, really odd. Wonder what was causing it. Will keep playing for a little longer just to be sure and report back if anything else happens.

**Comment by mgemperl** [comment]
Thanks for the update. When the same issue happens, instead of crashing, this current version will ignore whatever party it was trying to train and display a popup box. If you don't encounter that, then whatever the underlying problem was is gone for some reason.
