### ISSUE TITLE
Training tweak crashes while playing game

### ISSUE THREAD

**Issue by Zhourias** [mgemperl/TrainingTweak#3]
![agasdasd](https://user-images.githubusercontent.com/35023638/82279962-db0d6180-99e1-11ea-9fa8-2c59e244305b.PNG)

This is the error i get while playing. I am able to keep playing but training tweak doesnt work

**Comment by mgemperl** [comment]
Ah, if you haven't opted in to the game's beta branch and you're still on game version e1.4.0, then you'll get that error while using mod version 1.1.0 or 1.1.0s, which were made for game version 
e1.4.1 (the current beta branch version).

If you're still on game version e1.4.0, you'll want to continue using mod version 1.0.9h2 or 1.0.9s until the game's stable branch is updated to version e1.4.1.

Please let me know if you're actually getting that error while on game version e1.4.1 though.
